# site settings
title: Ian A Dalton
subtitle: Data Scientist
email: ian.ad@gmx.us
description: Data-oriented cognitive scientist with project management and research administration experience. I build data wrangling and analysis pipelines in Python and R.
baseurl: "/forty-jekyll-theme" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author: ianad
street_address: 7802 Pine Crossing Circle
city: Orlando
state: FL
zip_code: 32807
country: United States of America
phone: (561) 707-5588

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url: https://github.com/ianad
gitlab_url: https://gitlab.com/u/ianad
googleplus_url: 
instagram_url: 
linkedin_url: https://www.linkedin.com/in/ian-ad
pinterest_url:
slack_url:
twitter_url: https://twitter.com/ian_cogneato

# build settings
markdown: kramdown

sass:
  style: compressed
